name: database-schema-migration

channels: 
  - default

dependencies:
  - python=3.7
  - psycopg2=2.8.5
  - alembic=1.4.2
  - certifi=2022.9.24
  - greenlet=2.0.1
  - importlib-metadata=4.11.3
  - Mako=1.2.3
  - MarkupSafe=2.1.1
  - pip=22.2.2
  - psycopg2=2.8.5
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - setuptools=65.5.0
  - six=1.16.0
  - SQLAlchemy=1.4.44
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - zipp=3.8.0
